services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak

    command:
      - start-dev
      - --import-realm

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    volumes:
      - ./keycloak:/opt/keycloak/data/import

    networks:
      - whiteboard-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - keycloak
    networks:
      - whiteboard-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - whiteboard-network

networks:
  whiteboard-network:
    driver: bridge
